version: "3.7"

services:
  db:
   image: postgres:13.1
   restart: always
   environment:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 1234
   ports:
    - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:4.28
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: alexis.lepretre@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 80
    ports:
     - '8090:80'
    links:
     - "db:pgsql-server"