CREATE TABLE  users(
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE cats(
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    race VARCHAR (100) NOT NULL
);